In [3]:
import pandas as pd
import numpy as np

In [5]:
nomads_all_merged=pd.read_csv('../data/clean/nomads_all_merged.csv', sep=";")

In [7]:
nomads_all_merged

,rank,city,country,country_code,meal,mcdonalds,beer,coffee,monthly_pass,monthly_rent,...,climate_value,climate_category,cost_of_living_value,cost_of_living_category,pollution_value,pollution_category,quality_of_life_value,quality_of_life_category,internet_speed,digital_nomads_count
0,1,Bangkok,Thailand,TH,3.0,5.0,2.0,2.0,36.0,567.0,...,69.76,High,33.88,Very Low,75.65,High,105.37,Low,225.17,622.0
1,2,Da Nang,Vietnam,VN,2.0,4.0,1.0,2.0,7.0,312.0,...,71.24,High,26.85,Very Low,84.19,Very High,97.18,Very Low,78.34,60.0
2,3,Kuala Lumpur,Malaysia,MY,3.0,4.0,2.0,3.0,22.0,418.0,...,56.55,Moderate,29.82,Very Low,61.14,High,136.22,Moderate,107.55,337.0
3,4,Cape Town,South Africa,ZA,8.0,4.0,1.0,2.0,28.0,658.0,...,95.25,Very High,31.30,Very Low,56.56,Moderate,155.84,High,54.75,97.0
4,5,Buenos Aires,Argentina,AR,6.0,5.0,1.0,2.0,10.0,297.0,...,98.28,Very High,32.65,Very Low,50.81,Moderate,115.06,Low,58.87,156.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,1364,Dar es Salaam,Tanzania,TZ,2.0,6.0,1.0,2.0,5.0,318.0,...,71.28,High,25.31,Very Low,62.48,High,0.00,Very Low,19.77,12.0
1300,1365,Saint Petersburg,Russia,RU,10.0,6.0,1.0,2.0,23.0,395.0,...,43.60,Moderate,25.25,Very Low,59.13,Moderate,113.56,Low,95.96,57.0
1301,1366,Yangon,Myanmar,MM,3.0,5.0,1.0,2.0,23.0,317.0,...,0.00,NaN,35.88,Very Low,89.79,Very High,0.00,NaN,20.69,40.0
1302,1368,Tehran,Iran,IR,4.0,5.0,0.0,1.0,16.0,516.0,...,70.99,High,24.03,Very Low,75.24,High,85.42,Very Low,21.36,11.0
1303,1369,Moscow,Russia,RU,12.0,6.0,1.0,3.0,37.0,1088.0,...,43.60,Moderate,25.25,Very Low,59.13,Moderate,113.56,Low,95.96,84.0

In [9]:
# Create the new column using equal-width binning
nomads_all_merged['internet_speed_category'] = pd.cut(
    nomads_all_merged['internet_speed'],
    bins=5,  # Divide the range into 5 equal intervals
    labels=["Very Slow", "Slow", "Moderate", "Fast", "Very Fast"]
)

In [42]:
# Min-max normalization (inverted) to scale between 0 and 5
min_val = nomads_all_merged['cost_of_living_value'].min()
max_val = nomads_all_merged['cost_of_living_value'].max()

nomads_all_merged['cost_of_living_score'] = (
    (max_val - nomads_all_merged['cost_of_living_value']) / (max_val - min_val) * 5
).round(1)

In [44]:
nomads_all_merged.head(20)

,rank,city,country,country_code,meal,mcdonalds,beer,coffee,monthly_pass,monthly_rent,...,cost_of_living_value,cost_of_living_category,pollution_value,pollution_category,quality_of_life_value,quality_of_life_category,internet_speed,digital_nomads_count,internet_speed_category,cost_of_living_score
0,1,Bangkok,Thailand,TH,3.0,5.0,2.0,2.0,36.0,567.0,...,33.88,Very Low,75.65,High,105.37,Low,225.17,622.000000,Very Fast,3.8
1,2,Da Nang,Vietnam,VN,2.0,4.0,1.0,2.0,7.0,312.0,...,26.85,Very Low,84.19,Very High,97.18,Very Low,78.34,60.000000,Slow,4.0
2,3,Kuala Lumpur,Malaysia,MY,3.0,4.0,2.0,3.0,22.0,418.0,...,29.82,Very Low,61.14,High,136.22,Moderate,107.55,337.000000,Moderate,3.9
3,4,Cape Town,South Africa,ZA,8.0,4.0,1.0,2.0,28.0,658.0,...,31.30,Very Low,56.56,Moderate,155.84,High,54.75,97.000000,Slow,3.9
4,5,Buenos Aires,Argentina,AR,6.0,5.0,1.0,2.0,10.0,297.0,...,32.65,Very Low,50.81,Moderate,115.06,Low,58.87,156.000000,Slow,3.8
5,6,"Canggu, Bali",Indonesia,ID,2.0,3.0,2.0,2.0,10.0,210.0,...,25.31,Very Low,67.99,High,99.98,Very Low,27.83,6.000000,Very Slow,4.1
6,7,Melbourne,Australia,AU,15.0,9.0,4.0,3.0,103.0,1225.0,...,64.50,Moderate,26.80,Low,190.69,Very High,82.73,149.000000,Slow,2.7
7,8,Chiang Mai,Thailand,TH,2.0,5.0,2.0,2.0,20.0,252.0,...,33.88,Very Low,75.65,High,105.37,Low,225.17,552.000000,Very Fast,3.8
8,9,Ericeira,Portugal,PT,8.0,6.0,1.0,1.0,36.0,625.0,...,41.72,Low,28.80,Low,168.85,Very High,162.55,1.000000,Fast,3.5
9,10,Asuncion,Paraguay,PY,4.0,5.0,1.0,2.0,22.0,344.0,...,23.19,Very Low,66.16,High,109.45,Low,72.50,8.000000,Slow,4.2
10,11,Phuket,Thailand,TH,3.0,7.0,1.0,2.0,0.0,329.0,...,33.88,Very Low,75.65,High,105.37,Low,225.17,176.000000,Very Fast,3.8
11,12,Mexico City,Mexico,MX,7.0,6.0,1.0,3.0,15.0,731.0,...,35.00,Very Low,58.46,Moderate,127.02,Moderate,54.88,170.000000,Slow,3.7
12,13,Auckland,New Zealand,NZ,15.0,9.0,3.0,3.0,131.0,1305.0,...,59.36,Low,26.00,Low,186.57,Very High,170.51,94.000000,Fast,2.8
13,14,Tokyo,Japan,JP,7.0,5.0,2.0,3.0,71.0,1087.0,...,46.99,Low,38.55,Low,184.32,Very High,178.76,311.000000,Fast,3.3
14,15,Weligama,Sri Lanka,LK,1.0,4.0,1.0,1.0,5.0,110.0,...,33.96,Very Low,57.94,Moderate,75.17,Very Low,26.08,2.000000,Very Slow,3.8
15,16,Timisoara,Romania,RO,6.0,5.0,1.0,2.0,20.0,374.0,...,34.66,Very Low,58.61,Moderate,142.14,Moderate,232.17,14.000000,Very Fast,3.7
16,18,Tbilisi,Georgia,GE,10.0,7.0,1.0,2.0,14.0,760.0,...,32.00,Very Low,67.54,High,125.48,Moderate,28.61,33.000000,Very Slow,3.8
17,19,Ljubljana,Slovenia,SI,10.0,6.0,1.0,2.0,37.0,671.0,...,47.58,Low,22.25,Low,178.94,Very High,115.61,42.000000,Moderate,3.3
18,20,Portimao,Portugal,PT,8.0,7.0,1.0,2.0,20.0,610.0,...,41.72,Low,28.80,Low,168.85,Very High,162.55,6.000000,Fast,3.5
19,21,Ploiesti,Romania,RO,7.0,5.0,1.0,2.0,24.0,325.0,...,34.66,Very Low,58.61,Moderate,142.14,Moderate,232.17,19.833333,Very Fast,3.7

In [20]:
trip_df_cleaned=pd.read_csv('../data/clean/trip_df_cleaned.csv', sep=";")

In [22]:
trip_df_cleaned

,id,username,country,country_code,city,date_start,date_end,day_travel,latitude,longitude
0,1,@lewellenmichael,Mexico,MX,Guanajuato,2018-06-04,2018-06-15,11,21.0,-101.0
1,2,@lewellenmichael,Mexico,MX,Mexico City,2018-05-31,2018-06-03,3,19.0,-99.0
2,3,@lewellenmichael,Mexico,MX,Cancun,2017-11-01,2017-11-05,4,21.0,-86.0
3,4,@lewellenmichael,Jordan,JO,Amman,2017-07-24,2017-08-07,14,31.0,35.0
4,5,@waylandchin,China,CN,Yingkou,2017-02-17,2017-03-18,29,40.0,122.0
...,...,...,...,...,...,...,...,...,...,...
42414,46271,@antonioc,Cuba,CU,Cuba,2016-05-19,2016-05-25,6,21.0,-77.0
42415,46272,@antonioc,Costa Rica,CR,Costa Rica,2016-04-28,2016-05-18,20,9.0,-83.0
42416,46273,@antonioc,United States,US,Philadelphia,2016-04-04,2016-04-26,22,39.0,-75.0
42417,46274,@jrearden,United States,US,Destin,2018-05-12,2018-05-19,7,30.0,-86.0
42418,46275,@kschroeder,Argentina,AR,Mar del Plata,2018-01-12,2018-02-08,27,-38.0,-57.0

In [26]:
users_wework=pd.read_csv('../data/clean/users_wework.csv', sep=";")

In [34]:
users_wework['coworking_potential_category'] = pd.qcut(
    users_wework['coworking_potential'],
    q=5,
    labels=["Very Low", "Low", "Moderate", "High", "Very High"]
)

In [38]:
# Min-max normalization to scale between 0 and 5
min_val = users_wework['coworking_potential'].min()
max_val = users_wework['coworking_potential'].max()

users_wework['coworking_potential_score'] = (
    (users_wework['coworking_potential'] - min_val) / (max_val - min_val) * 5
).round(1)

In [40]:
users_wework

,country,country_code,digital_nomads_count,wework_count,digital_nomads_ratio,wework_ratio,coworking_potential,coworking_potential_category,coworking_potential_score
0,United States,US,1137,85.0,7.94,20.58,-12.64,Very Low,0.7
1,Thailand,TH,947,3.0,6.62,0.73,5.89,Very High,5.0
2,Spain,ES,731,9.0,5.11,2.18,2.93,Very High,4.3
3,Germany,DE,643,13.0,4.49,3.15,1.34,High,3.9
4,United Kingdom,GB,600,31.0,4.19,7.51,-3.32,Very Low,2.9
5,Indonesia,ID,590,3.0,4.12,0.73,3.39,Very High,4.4
6,France,FR,506,7.0,3.53,1.69,1.84,Very High,4.1
7,Portugal,PT,413,1.0,2.89,0.24,2.65,Very High,4.2
8,Netherlands,NL,411,4.0,2.87,0.97,1.90,Very High,4.1
9,Vietnam,VN,398,2.0,2.78,0.48,2.30,Very High,4.2
10,Italy,IT,394,4.0,2.75,0.97,1.78,Very High,4.0
11,China,CN,393,76.0,2.75,18.40,-15.65,Very Low,0.0
12,Malaysia,MY,387,2.0,2.70,0.48,2.22,Very High,4.1
13,Japan,JP,378,38.0,2.64,9.20,-6.56,Very Low,2.1
14,Mexico,MX,349,8.0,2.44,1.94,0.50,Low,3.7
15,Singapore,SG,333,13.0,2.33,3.15,-0.82,Very Low,3.4
16,Canada,CA,313,16.0,2.19,3.87,-1.68,Very Low,3.2
17,Australia,AU,299,15.0,2.09,3.63,-1.54,Very Low,3.3
18,Hungary,HU,290,0.0,2.03,0.00,2.03,Very High,4.1
19,Colombia,CO,248,11.0,1.73,2.66,-0.93,Very Low,3.4
20,Czechia,CZ,217,1.0,1.52,0.24,1.28,High,3.9
21,Croatia,HR,204,0.0,1.43,0.00,1.43,High,4.0
22,Austria,AT,201,0.0,1.40,0.00,1.40,High,4.0
23,Cambodia,KH,195,0.0,1.36,0.00,1.36,High,3.9
24,South Korea,KR,188,18.0,1.31,4.36,-3.05,Very Low,2.9
25,Greece,GR,185,0.0,1.29,0.00,1.29,High,3.9
26,Argentina,AR,180,4.0,1.26,0.97,0.29,Low,3.7
27,Switzerland,CH,174,0.0,1.22,0.00,1.22,High,3.9
28,Brazil,BR,173,6.0,1.21,1.45,-0.24,Low,3.6
29,Taiwan,TW,170,1.0,1.19,0.24,0.95,Moderate,3.9
30,Sweden,SE,166,1.0,1.16,0.24,0.92,Moderate,3.8
31,India,IN,165,21.0,1.15,5.08,-3.93,Very Low,2.7
32,Philippines,PH,163,3.0,1.14,0.73,0.41,Low,3.7
33,Poland,PL,159,5.0,1.11,1.21,-0.10,Low,3.6
34,New Zealand,NZ,157,0.0,1.10,0.00,1.10,High,3.9
35,Denmark,DK,157,0.0,1.10,0.00,1.10,High,3.9
36,Ireland,IE,154,4.0,1.08,0.97,0.11,Low,3.7
37,Turkey,TR,148,0.0,1.03,0.00,1.03,High,3.9
38,Belgium,BE,147,1.0,1.03,0.24,0.79,Moderate,3.8
39,Morocco,MA,137,0.0,0.96,0.00,0.96,Moderate,3.9
40,Peru,PE,137,0.0,0.96,0.00,0.96,Moderate,3.9
41,United Arab Emirates,AE,125,2.0,0.87,0.48,0.39,Low,3.7
42,Serbia,RS,116,0.0,0.81,0.00,0.81,Moderate,3.8
43,South Africa,ZA,113,3.0,0.79,0.73,0.06,Low,3.6
44,Costa Rica,CR,111,2.0,0.78,0.48,0.30,Low,3.7
45,Chile,CL,108,0.0,0.75,0.00,0.75,Moderate,3.8
46,Norway,NO,105,0.0,0.73,0.00,0.73,Moderate,3.8
47,Russia,RU,104,0.0,0.73,0.00,0.73,Moderate,3.8
48,Romania,RO,100,0.0,0.70,0.00,0.70,Moderate,3.8
49,Bulgaria,BG,96,0.0,0.67,0.00,0.67,Low,3.8

In [46]:
nomads_all_merged = nomads_all_merged.merge(
    users_wework[['country_code', 'coworking_potential_score']],
    on='country_code',
    how='left'
)

# Fill missing values with 0
nomads_all_merged['coworking_potential_score'] = nomads_all_merged['coworking_potential_score'].fillna(0)

In [48]:
nomads_all_merged

,rank,city,country,country_code,meal,mcdonalds,beer,coffee,monthly_pass,monthly_rent,...,cost_of_living_category,pollution_value,pollution_category,quality_of_life_value,quality_of_life_category,internet_speed,digital_nomads_count,internet_speed_category,cost_of_living_score,coworking_potential_score
0,1,Bangkok,Thailand,TH,3.0,5.0,2.0,2.0,36.0,567.0,...,Very Low,75.65,High,105.37,Low,225.17,622.0,Very Fast,3.8,5.0
1,2,Da Nang,Vietnam,VN,2.0,4.0,1.0,2.0,7.0,312.0,...,Very Low,84.19,Very High,97.18,Very Low,78.34,60.0,Slow,4.0,4.2
2,3,Kuala Lumpur,Malaysia,MY,3.0,4.0,2.0,3.0,22.0,418.0,...,Very Low,61.14,High,136.22,Moderate,107.55,337.0,Moderate,3.9,4.1
3,4,Cape Town,South Africa,ZA,8.0,4.0,1.0,2.0,28.0,658.0,...,Very Low,56.56,Moderate,155.84,High,54.75,97.0,Slow,3.9,3.6
4,5,Buenos Aires,Argentina,AR,6.0,5.0,1.0,2.0,10.0,297.0,...,Very Low,50.81,Moderate,115.06,Low,58.87,156.0,Slow,3.8,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,1364,Dar es Salaam,Tanzania,TZ,2.0,6.0,1.0,2.0,5.0,318.0,...,Very Low,62.48,High,0.00,Very Low,19.77,12.0,Very Slow,4.1,0.0
1300,1365,Saint Petersburg,Russia,RU,10.0,6.0,1.0,2.0,23.0,395.0,...,Very Low,59.13,Moderate,113.56,Low,95.96,57.0,Slow,4.1,3.8
1301,1366,Yangon,Myanmar,MM,3.0,5.0,1.0,2.0,23.0,317.0,...,Very Low,89.79,Very High,0.00,NaN,20.69,40.0,Very Slow,3.7,0.0
1302,1368,Tehran,Iran,IR,4.0,5.0,0.0,1.0,16.0,516.0,...,Very Low,75.24,High,85.42,Very Low,21.36,11.0,Very Slow,4.1,0.0
1303,1369,Moscow,Russia,RU,12.0,6.0,1.0,3.0,37.0,1088.0,...,Very Low,59.13,Moderate,113.56,Low,95.96,84.0,Slow,4.1,3.8

In [74]:
# Step 1: Create a mask for top 100 ranks
top_100_mask = nomads_all_merged['rank'] <= 100

# Step 2: Get min and max from the filtered top 100
min_rank = nomads_all_merged.loc[top_100_mask, 'rank'].min()
max_rank = nomads_all_merged.loc[top_100_mask, 'rank'].max()

# Step 3: Create normalized score only for top 100
nomads_all_merged['nomad_web_score'] = 0  # Default to 0

nomads_all_merged.loc[top_100_mask, 'nomad_web_score'] = (
    (max_rank - nomads_all_merged.loc[top_100_mask, 'rank']) / (max_rank - min_rank) * 5
).round(1)

/var/folders/yn/zzdysdkj6_z0rns53nqvdbvr0000gn/T/ipykernel_18430/2119038449.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[5.  4.6 4.5 0.7 2.8 2.4 4.7 0.3 4.9 1.  2.  4.9 1.3 1.7 3.7 4.6 1.3 1.7
 3.5 3.7 3.6 3.9 4.8 4.8 2.7 4.  3.5 2.5 4.4 4.2 3.5 2.  2.7 1.8 0.  1.
 0.8 4.  3.  0.7 0.5 0.5 2.6 0.2 0.4 1.9 2.1 1.6 1.5 3.1 2.3 1.5 2.5 3.1
 2.2 0.4 1.1 3.4 3.6 4.4 3.  2.9 2.6 1.9 1.2 2.4 2.1 4.7 1.8 2.8 2.9 3.3
 3.8 4.3 3.8 0.1 4.5 3.2 0.6 0.2 0.3 4.3 4.1 1.6 1.4 1.1 0.9 0.6 1.4 0.9
 2.2 4.1 1.2 1.7 3.3 3.2 0.8 3.4 0.5 0.1 2.3 3.9]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  nomads_all_merged.loc[top_100_mask, 'nomad_web_score'] = (

In [85]:
min_val = nomads_all_merged['digital_nomads_count'].min()
max_val = nomads_all_merged['digital_nomads_count'].max()

nomads_all_merged['popularity_score'] = 1 + (
    (nomads_all_merged['digital_nomads_count'] - min_val) /
    (max_val - min_val)
) * 4

# Round to 1 decimal place
nomads_all_merged['popularity_score'] = nomads_all_merged['popularity_score'].round(1)

In [123]:
min_val = nomads_all_merged['safety_value'].min()
max_val = nomads_all_merged['safety_value'].max()

nomads_all_merged['safety_score'] = 1 + (
    (nomads_all_merged['safety_value'] - min_val) /
    (max_val - min_val)
) * 4

# Round to 1 decimal place
nomads_all_merged['safety_score'] = nomads_all_merged['safety_score'].round(1)

In [99]:
# Apply weights to each score
nomads_all_merged['coworking_potential_weighted_score'] = (
    nomads_all_merged['_score'] * 0.3 +
    nomads_all_merged['coworking_potential_score'] * 0.3 +
    nomads_all_merged['nomad_web_score'] * 0.2 +
    nomads_all_merged['popularity_score'] * 0.2
).round(2)

In [101]:
# Assign rank (1 = best, higher score = better rank)
nomads_all_merged['coworking_rank'] = nomads_all_merged['coworking_potential_weighted_score'].rank(
    method='dense',  # No gaps in ranking
    ascending=False  # Higher score = better rank (rank 1 is the best)
).astype(int)  # Convert to integer

# Sort by rank (best first)
nomads_all_merged = nomads_all_merged.sort_values(by='coworking_rank')

In [125]:
nomads_all_merged

,rank,city,country,country_code,meal,mcdonalds,beer,coffee,monthly_pass,monthly_rent,...,internet_speed,digital_nomads_count,internet_speed_category,cost_of_living_score,coworking_potential_score,coworking_potential_weighted_score,coworking_rank,nomad_web_score,popularity_score,safety_score
0,1,Bangkok,Thailand,TH,3.0,5.0,2.0,2.0,36.0,567.0,...,225.17,622.0,Very Fast,3.8,5.0,4.64,1,5.0,5.0,3.7
7,8,Chiang Mai,Thailand,TH,2.0,5.0,2.0,2.0,20.0,252.0,...,225.17,552.0,Very Fast,3.8,5.0,4.46,2,4.6,4.5,3.7
2,3,Kuala Lumpur,Malaysia,MY,3.0,4.0,2.0,3.0,22.0,418.0,...,107.55,337.0,Moderate,3.9,4.1,4.02,3,4.9,3.2,3.0
10,11,Phuket,Thailand,TH,3.0,7.0,1.0,2.0,0.0,329.0,...,225.17,176.0,Very Fast,3.8,5.0,3.96,4,4.5,2.1,3.7
20,22,Lisbon,Portugal,PT,12.0,7.0,1.0,2.0,40.0,1184.0,...,162.55,346.0,Fast,3.5,4.2,3.73,5,3.9,3.2,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,143,Oranjestad,Aruba,AW,11.0,8.0,3.0,2.0,48.0,734.0,...,NaN,4.0,NaN,2.1,0.0,0.83,180,0.0,1.0,4.1
1242,1289,Nuuk,Greenland,GL,16.0,15.0,4.0,6.0,75.0,946.0,...,NaN,1.0,NaN,2.0,0.0,0.80,181,0.0,1.0,3.6
1172,1210,Hamilton,Bermuda,BM,28.0,14.0,5.0,5.0,66.0,3098.0,...,NaN,10.0,NaN,0.5,0.0,0.37,182,0.0,1.1,3.7
1173,1210,Hamilton,Bermuda,BM,13.0,8.0,2.0,3.0,78.0,1137.0,...,NaN,10.0,NaN,0.5,0.0,0.37,182,0.0,1.1,3.7
598,605,Monaco,Monaco,MC,25.0,9.0,2.0,4.0,36.0,5233.0,...,NaN,19.0,NaN,0.0,0.0,0.22,183,0.0,1.1,4.5

In [109]:
users_work_ver=pd.read_csv('../data/clean/users_work_ver.csv', sep=";")

In [112]:
users_wework=pd.read_csv('../data/clean/users_wework.csv', sep=";")

In [127]:
# Define the file path for the Excel export
excel_file_path = "../data/clean/tableau_nomads.xlsx"

# Export Excel file with multiple sheets
with pd.ExcelWriter(excel_file_path, engine="xlsxwriter") as writer:
    nomads_all_merged.to_excel(writer, sheet_name="Nomads All Merged", index=False)
    trip_df_cleaned.to_excel(writer, sheet_name="Trip Data Cleaned", index=False)
    users_work_ver.to_excel(writer, sheet_name="Users Work Version", index=False)
    users_wework.to_excel(writer, sheet_name="Users Wework", index=False)
    
print(f"✅ Excel file saved successfully at: {excel_file_path}")

✅ Excel file saved successfully at: ../data/clean/tableau_nomads.xlsx